export type Mobil = {
  ID: string;
  nama: string;
  price: number;
  pelat: string;
  kapasitas_penumpang: number;
  status: boolean;
  kapasitas_mesin: number;
  photo_url?: string;
  user_id: string;
  tipe_mobil_id: number;
  tipe_persneling_id: number;
  tipe_mesin_id: number;
  tipe_mobil?: string;
  tipe_persneling?: string;
  tipe_mesin?: string;
  lokasi_id: string;
  lokasi?: string;
  rating: number;
};
